[package]
name = "actor_macros"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.70"
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full", "extra-traits"] }
