[package]
name = "world_service"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.94"
bevy = { version = "0.15.0", default-features = false }
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.22", features = ["derive"] }
cluster = { version = "0.1.0", path = "../../lib/cluster" }
core_api = { version = "0.1.0", path = "../../lib/core_api" }
futures-util = "0.3.31"
log = "0.4.22"
once_cell = "1.20.2"
protocol = { version = "0.1.0", path = "../../lib/protocol" }
realm_api = { version = "0.1.0", path = "../../lib/realm_api" }
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.4"
tokio = { version = "1.42.0", features = ["full"] }
toolkit = { version = "0.1.0", path = "../../lib/toolkit" }
zone = { version = "0.1.0", path = "../../lib/zone" }
