[package]
name = "cluster_router"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
raknet = { version = "0.1.0", path = "../../lib/raknet" }
tokio = { version = "1.40.0", features = ["full"] }
toolkit = { version = "0.1.0", path = "../../lib/toolkit" }
