[package]
name = "kismet-plotter"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
upk = { workspace = true }
