name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ v* ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    timeout-minutes: 240
      
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to the Container registry
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=edge,branch=main
          
    - name: Build and push Docker image
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64

    #- uses: actions-hub/kubectl@master
    #  env:
    #    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #  with:
    #    args: rollout restart deployment anotherland-deployment -n otherland
